services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    networks:
      - backend

  discovery-server:
    image: halilibrahimtas/discovery-server
    ports:
      - 8761:8761
    mem_limit: 700m
    depends_on:
      - keycloak
    networks:
      - backend

  api-gateway:
    image: halilibrahimtas/api-gateway
    ports:
      - 8181:8181
    mem_limit: 700m
    depends_on:
      - discovery-server
    networks:
      - backend

  car-service:
    image: halilibrahimtas/car-service
    ports:
      - 6005:6005
    mem_limit: 700m
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - backend

  rental-service:
    image: halilibrahimtas/rental-service
    ports:
      - 7005:7005
    mem_limit: 700m
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rentals
    networks:
      - backend

networks:
  backend:
    driver: bridge