services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

  postgresql-rentals:
    image: postgres:latest
    container_name: postgresql-rentals
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rentals
    networks:
      - backend

  postgresql-customers:
    image: postgres:latest
    container_name: postgresql-customers
    ports:
       - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: customers
    networks:
      - backend

networks:
  backend:
    driver: bridge