services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    networks:
      - backend

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    mem_limit: 700m

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend

  postgresql:
    image: postgres:latest
    container_name: postgresql-rentals
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_MULTIPLE_DATABASES: rentals, customers
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-manager:
    image: hlebalbau/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka

  customer-service:
    build: ./customer-service
    ports:
      - "7001:7001"
    mem_limit: 700m
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - currency-network

  rental-service:
    build: ./rental-service
    ports:
      - "7002:7002"
    mem_limit: 700m
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
    depends_on:
      - discovery-server
      - api-gateway
      - notification-service
    networks:
      - currency-network

  notification-service:
    build: ./notification-service
    ports:
      - "7003:7003"
    mem_limit: 700m
    depends_on:
      - kafka
    networks:
      - currency-network

  car-service:
    build: ./car-service
    ports:
      - "7004:7004"
    mem_limit: 700m
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
    depends_on:
      - discovery-server
      - api-gateway
    networks:
      - currency-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8181:8181"
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://localhost:8761/eureka
    depends_on:
      - discovery-server
    networks:
      - currency-network

networks:
  backend:
    driver: bridge